app:
  jwt:
    secret-key: ff0d5cc9e17cedaafd741b7a198cb90a
  paths:
    video-folder: /VIDEO
    subtitle-folder: subtitles

spring:
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000
        shutdown-timeout: 1000



